config/routes.rb
ProjectMonitor::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", sessions: "sessions" }
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  get 'builds' => "home#builds", format: :rss
  get 'version' => 'versions#show'
  get 'github_status' => 'home#github_status', format: :json
  get 'heroku_status' => 'home#heroku_status', format: :json
  get 'rubygems_status' => 'home#rubygems_status', format: :json

  post 'projects/validate_tracker_project'
  patch 'projects/validate_build_info'

  resource :configuration, only: [:show, :create, :edit], controller: "configuration"
  resources :users, only: [:new, :create]
  resources :projects do
    resources :payload_log_entries, only: :index
    resource :status, only: :create, controller: "status"
    member do
      get :status
    end
  end
  resources :aggregate_projects do
    member do
      get :status
    end
    resources :projects, only: [:index]
  end

  authenticate :user do
    get "/jobs" => DelayedJobWeb, anchor: false
  end

  get 'styleguide' => 'home#styleguide'
  root to: 'home#index'
end

app/models/project.rb
class Project < ActiveRecord::Base

  RECENT_STATUS_COUNT = 8
  DEFAULT_POLLING_INTERVAL = 30
  MAX_STATUS = 15

  has_many :statuses,
    class_name: 'ProjectStatus',
    dependent: :destroy,
    before_add: :update_refreshed_at
  has_many :recent_statuses, -> { recent(RECENT_STATUS_COUNT) }, class_name: "ProjectStatus"

  has_many :payload_log_entries
  has_one :latest_payload_log_entry, -> { recent(1) }, class_name: "PayloadLogEntry"

  belongs_to :aggregate_project
  belongs_to :creator, class_name: 'User'

  serialize :last_ten_velocities, Array
  serialize :iteration_story_state_counts, JSON
  serialize :tracker_validation_status, Hash

  scope :enabled, -> { where(enabled: true) }
  scope :standalone, -> { where(aggregate_project_id: nil) }
  scope :with_statuses, -> { joins(:statuses).uniq }

  scope :updateable, -> {
    enabled.where(webhooks_enabled: [nil, false])
  }

  scope :tracker_updateable, -> {
    enabled
    .where.not(tracker_auth_token: [nil, ''])
    .where.not(tracker_project_id: [nil, ''])
  }

  scope :displayable, lambda { |tags|
    scope = enabled.order('code ASC')
    return scope.tagged_with(tags, any: true) if tags
    scope
  }

  acts_as_taggable

  validates :name, presence: true
  validates :type, presence: true

  before_create :generate_guid
  before_create :populate_iteration_story_state_counts

  before_save :trim_urls_and_tokens

  attr_writer :feed_url

  delegate :success?, :indeterminate?, :failure?, :color, to: :state

  def populate_iteration_story_state_counts
    self.iteration_story_state_counts = []
  end

  def self.project_specific_attributes
    ["ci_build_identifier", "ci_base_url"]
  end

  def self.with_aggregate_project(aggregate_project_id, &block)
    where(aggregate_project_id: aggregate_project_id).scoping(&block)
  end

  def code
    super.presence || name && name.downcase.gsub(" ", '')[0..3]
  end

  def latest_status
    recent_statuses.first
  end

  def status
    latest_status || ProjectStatus.new(project: self)
  end

  def requires_branch_name?
    false
  end

  def red_since
    breaking_build.try(:published_at)
  end

  def red_build_count
    return 0 if breaking_build.nil? || !online?
    statuses.red.where('id >= ?', breaking_build.id).count
  end

  def feed_url
    raise NotImplementedError, 'Must implement feed_url in subclasses'
  end

  def build_status_url
    raise NotImplementedError, 'Must implement build_status_url in subclasses'
  end

  def tracker_project_url
    "https://www.pivotaltracker.com/services/v3/projects/#{tracker_project_id}"
  end

  def tracker_iterations_url
    "https://www.pivotaltracker.com/services/v3/projects/#{tracker_project_id}/iterations/done?offset=-10"
  end

  def tracker_current_iteration_url
    "https://www.pivotaltracker.com/services/v3/projects/#{tracker_project_id}/iterations/current"
  end

  def to_s
    name
  end

  def last_green
    @last_green ||= recent_statuses.green.first
  end

  def breaking_build
    @breaking_build ||= if last_green.nil?
                          recent_statuses.red.last
                        else
                          recent_statuses.red.where('build_id > ?', last_green.build_id).first
                        end
  end

  def has_auth?
    auth_username.present? || auth_password.present?
  end

  def tracker_project?
    tracker_project_id.present? && tracker_auth_token.present?
  end
  alias tracker_configured?  tracker_project?

  def payload
    raise NotImplementedError, 'Must implement payload in subclasses'
  end

  def has_status?(status)
    statuses.where(build_id: status.build_id).any?
  end

  def has_dependencies?
    false
  end

  def generate_guid
    self.guid = SecureRandom.uuid
  end

  def volatility
    @volatility ||= Volatility.calculate(last_ten_velocities)
  end

  def published_at
    latest_status.try(:published_at)
  end

  def accept_mime_types
    nil
  end

  def state
    State.new(online: online, success: latest_status.try(:success?))
  end

  # FIXME: This method shouldn't be a method of Project class
  def url_with_scheme(url)
    url =~ %r{\Ahttps?://} ? url : "http://#{url}"
  end

  def self.project_attribute_prefix
    name.match(/(.*)Project/)[1].underscore
  end

  def webhook_payload
    fetch_payload
  end
  
  private

  def trim_urls_and_tokens
    self.class.columns.select{|column| column.name.end_with?('_url', '_token') }.each do |column|
      write_attribute(column.name, read_attribute(column.name).try(:strip))
    end
  end

  def update_refreshed_at(status)
    self.last_refreshed_at = Time.now if online?
  end

  def fetch_statuses
    Delayed::Job.enqueue(StatusFetcher::Job.new(self), priority: 0)
  end

end

app/models/project/state.rb
class Project::State
  def initialize(online: false, success: nil)
    state_text = if !online
                   'offline'
                 elsif 'failed'
                   'failure'
                 elsif success
                   'success'
                 else
                   'indeterminate'
                 end
    @state = ActiveSupport::StringInquirer.new(state_text)
  end

  delegate :failure?, :success?, :indeterminate?, :offline?, :to_s, to: :state

  def self.success
    new(online: true, success: true)
  end

  def self.failure
    new(online: true, success: false)
  end

  def self.offline
    new(online: false, success: nil)
  end

  def self.indeterminate
    new(online: true, success: nil)
  end

  def online?
    !offline?
  end

  def color
    {
      'offline' => 'white',
      'success' => 'green',
      'failure' => 'red',
      'indeterminate' => 'yellow'
    }[state.to_s]
  end

  def eql?(other)
    to_s.eql?(other.to_s)
  end

  def hash
    to_s.hash
  end

  private

  attr_reader :state

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_filter :authenticate_user!, only: [:show, :status, :index]
  before_filter :load_project, only: [:edit, :update, :destroy]
  around_filter :scope_by_aggregate_project

  DEFAULT_PROJECTS_TO_DISPLAY = 100

  respond_to :json, only: [:index, :show]

  def index
    if params[:aggregate_project_id].present?
      projects = AggregateProject.find(params[:aggregate_project_id]).projects.includes(:recent_statuses, :tags).decorate
    else
      standalone_projects = Project.limit(project_limit).standalone.displayable(params[:tags]).includes(:recent_statuses, :tags).decorate
      aggregate_projects = AggregateProject.displayable(params[:tags]).decorate
      projects = standalone_projects + aggregate_projects
    end
    @projects = projects.sort_by(&:code)

    respond_with @projects
  end

  def new
    @project = Project.new
  end

  def create
    klass = params[:project][:type].present? ? ProjectTypeHelper.find_type(params[:project][:type]) : Project
    @project = klass.new(project_params)
    @project.creator = current_user
    if @project.save
      redirect_to edit_configuration_path, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def show
    respond_with Project.find(params[:id])
  end

  def update
    if params[:password_changed] != 'true'
      params[:project].delete(:auth_password)
    else
      params[:project][:auth_password] = nil unless params[:project][:auth_password].present?
    end

    Project.transaction do
      old_class = @project.class
      if params[:project][:type] && @project.type != params[:project][:type]
        @project = @project.becomes(ProjectTypeHelper.find_type(params[:project][:type]))
        if project = Project.where(id: @project.id)
          project.update_all(type: params[:project][:type])
        end
      end

      if @project.update_attributes(project_params)
        redirect_to edit_configuration_path, notice: 'Project was successfully updated.'
      else
        if project = Project.where(id: @project.id)
          project.update_all(type: old_class.name)
        end
        render :edit
        raise ActiveRecord::Rollback
      end
    end
  end

  def destroy
    @project.destroy
    redirect_to edit_configuration_path, notice: 'Project was successfully destroyed.'
  end

  def validate_build_info
    head(422) and return if !params.has_key?(:project)

    project_id = params[:project][:id]
    project = project_id.present? ?
      Project.find(project_id).tap { |p| p.assign_attributes(project_params) } :
      ProjectTypeHelper.find_type(params[:project][:type]).new(project_params)

    status_updater = StatusUpdater.new
    project_updater = ProjectUpdater.new(
      PayloadProcessor.new(project_status_updater: status_updater),
      ProjectPollingStrategyFactory.new
    )
    log_entry = project_updater.update(project)

    render json: {
      status: log_entry.status == 'successful',
      error_type: log_entry.error_type,
      error_text: log_entry.error_text.to_s[0,10000]
    }
  end

  def validate_tracker_project
    project = Project.find(params[:id])
    status = :accepted
    if project.tracker_validation_status.present? &&
      project.tracker_validation_status[:auth_token] == params[:auth_token] &&
      project.tracker_validation_status[:project_id] == params[:project_id]
      status = project.tracker_validation_status[:status]
    else
      TrackerProjectValidator.delay(priority: 0).validate(params)
      project.tracker_validation_status = {auth_token: params[:auth_token], project_id: params[:project_id], status: :accepted}
      project.save!
    end
    head status
  end

  private

  def load_project
    @project = Project.find(params[:id])
  end

  def scope_by_aggregate_project
    if aggregate_project_id = params[:aggregate_project_id]
      Project.with_aggregate_project aggregate_project_id do
        yield
      end
    else
      yield
    end
  end

  def project_params
    params.require(:project).permit(%i(aggregate_project_id auth_password auth_username
                                       build_branch code cruise_control_rss_feed_url enabled
                                       jenkins_base_url jenkins_build_name name online
                                       semaphore_api_url tag_list tddium_auth_token tddium_base_url tddium_project_name
                                       team_city_base_url team_city_build_name tracker_auth_token
                                       tracker_online tracker_project_id travis_github_account
                                       travis_repository type webhooks_enabled
                                       circleci_username circleci_project_name circleci_auth_token travis_pro_token
                                       concourse_base_url concourse_job_name ci_base_url ci_build_identifier ci_auth_token
                                       concourse_pipeline_name id team_name))
  end

  def project_limit
    if params[:limit].present?
      (params[:limit] == 'all') ? nil : params[:limit]
    else
      DEFAULT_PROJECTS_TO_DISPLAY
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  PROJECT_META = YAML.load(File.read(Rails.root.join('config', 'project-meta.yml'))).with_indifferent_access

  PROJECT_TYPE_NAMES = PROJECT_META[:types].map(&:constantize)

  def project_types
    [['', '']] + PROJECT_TYPE_NAMES.map do |type_class|
      [t("project_types.#{type_class.name.underscore}"), type_class.name]
    end
  end

  def project_webhooks_url(project)
    if project.guid.present?
      'Your webhooks URL is ' + project_status_url(project.guid).to_s
    else
      unless project.new_record?
        project.generate_guid
        project.save!
      end
      ''
    end
  end

  def project_refreshed_at(project)
    if (refreshed_at = project.last_refreshed_at).present?
      t('helpers.projects.last_refreshed_at', time: l(refreshed_at, format: :short), date: l(refreshed_at.to_date, format: :short))
    end
  end

  def project_latest_error(project)
    project.latest_payload_log_entry.try { |l| "#{l.error_type}: '#{l.error_text}'" }
  end

  def project_last_status_text(project)
    if latest = project.latest_payload_log_entry
      if project.enabled
        latest.status || 'Unknown Status'
      else
        'disabled'
      end
    else
      'none'
    end.titleize
  end

  def project_last_status(project)
    if latest = project.latest_payload_log_entry
      if project.enabled?
        content_tag(:span, class: "last_status #{latest.status}") do
          color_class = {
            'successful' => 'text-success',
            'failed' => 'text-danger'
          }[latest.status]
          content_tag(:a, latest, href: project_payload_log_entries_path(project), class: color_class)
        end
      else
        content_tag(:span, class: "last_status #{latest.status}") do
          content_tag(:p, 'Disabled')
        end
      end
    else
      'None'
    end
  end

  ProjectAttribute = Struct.new(:name, :label, :tooltip)

  def project_specific_attributes_for(project_class)
    project_key = project_class.name.underscore

    project_class.project_specific_attributes.each_with_object({}) do |field_name, hash|
      label = PROJECT_META[:labels].try(:[], field_name).try(:[], project_key)
      tooltip = PROJECT_META[:tooltips].try(:[], field_name).try(:[], project_key)

      hash[field_name.to_sym] = ProjectAttribute.new(field_name, label, tooltip)
    end
  end

  def build_setup_instructions_for(project_type)
    file_name = project_type.to_s.underscore + '.md'
    markdown = File.read(Rails.root.join('docs', 'adding_a_project', file_name)) rescue ''
    markdown = remove_header_for_markdown(markdown)
    Kramdown::Document.new(markdown).to_html
  end

  private

  def remove_header_for_markdown(markdown)
    header_regex = (/(#+.*\n+)/)
    markdown.sub(header_regex, '')
  end
end

app/views/projects/_build_setup.html.haml
%hr
%fieldset#build_setup
  %h3 Build Setup
  .form-group
    = f.label :webhooks_enabled, 'Payload Strategy', class: 'col-sm-2 control-label'
    .col-sm-10
      .radio.row
        = f.label :webhooks_enabled_true do
          .col-sm-1
            = f.radio_button :webhooks_enabled, true
            Webhooks
          .col-sm-10.col-sm-offset-1
            %span#webhook_url.text-muted= project_webhooks_url(f.object)
      .radio
        = f.label :webhooks_enabled_false do
          = f.radio_button :webhooks_enabled, false
          Polling
  .form-group#branch_name{ class: f.object.requires_branch_name? ? nil : 'hide' }
    = f.label :build_branch, 'Branch Name', class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :build_branch, class: 'form-control'
    %p.help-block Default is 'master'. Codeship projects can utilize regex matching.
  #field_container
    - ProjectsHelper::PROJECT_TYPE_NAMES.each do |project_type|
      - enabled = f.object.type == project_type.name
      .project-attributes{ id: project_type,  class: "#{'hide' unless enabled}" }
        - project_specific_attributes_for(project_type).each do |field, field_attributes|
          .form-group
            = f.label field, field_attributes.label, class: 'col-sm-2 control-label'
            .col-sm-4
              = f.text_field field, disabled: !enabled, class: 'form-control'
            - if field_attributes.tooltip
              %p.help-block= field_attributes.tooltip
  %fieldset#polling
    .form-group.auth_field
      = f.label :auth_username, 'Feed Username', class: 'col-sm-2 control-label'
      .col-sm-4
        = f.text_field :auth_username, size: 40, class: 'optional form-control', autocomplete: 'off'
      %p.help-block Basic or digest authentication
    .form-group.auth_field
      = f.label :auth_password, 'Feed Password', class: 'col-sm-2 control-label'
      .col-sm-4
        %input{ id: 'password_changed', name: 'password_changed', type: 'hidden', value: 'false' }
        = f.password_field :auth_password, class: 'form-control', disabled: true
      %p.help-block
        - if f.object.auth_password.present?
          %span.label.label-success Saved
        - else
          %span.label.label-default Not Set
        %button{id: 'change_password', class: 'button-link'} Change password
    .form-group
      = f.label :online, 'CI status', class: 'col-sm-2 control-label'
      = f.hidden_field :online
      .col-sm-4
        %p.help-block#build_status
          %span.label.label-success.success.hide OK
          %span.label.label-info.pending.hide Loading...
          %span.label.label-default.unconfigured.hide Unconfigured
          %span.label.label-danger.failure.hide Error
          %span.label.label-warning.empty_fields.hide Some Fields Empty
          &nbsp;
          %input{ class: 'refresh btn btn-default btn-xs', type: 'button', value: 'Refresh' }
          %span{:class => 'error-message hide'}
    .row
      .col-sm-offset-2.col-sm-10
        %p.text-muted= project_refreshed_at(f.object)

app/views/projects/_form.html.haml
.form-group
  = f.label :code, class: 'col-sm-2 control-label'
  .col-sm-1
    = f.text_field :code, maxlength: 4, class: 'form-control'
.form-group
  = f.label :name, class: 'col-sm-2 control-label'
  .col-sm-4
    = f.text_field :name, class: 'form-control'
- if f.object.creator.present?
  .form-group
    = f.label :creator, class: 'col-sm-2 control-label'
    .col-sm-4
      %p.help-block
        = "#{f.object.creator.name} (#{f.object.creator.email})"
.form-group
  .col-sm-offset-2.col-sm-2
    .checkbox
      = f.label :enabled do
        = f.check_box :enabled
        Enabled?
.form-group
  = f.label :aggregate_project_id, 'Aggregate Project', class: 'col-sm-2 control-label'
  .col-sm-3
    = collection_select(:project, :aggregate_project_id, AggregateProject.all, :id, :name, {prompt: false, disabled: lambda { |ap| !ap.enabled? }, include_blank: true}, class: 'form-control')
.form-group
  :javascript
    autocomplete("#project_tag_list", #{ ActsAsTaggableOn::Tag.all.map(&:name) });
  = f.label :tag_list, 'Tags', class: 'col-sm-2 control-label'
  .col-sm-4
    = f.text_field :tag_list, value: f.object.tag_list.to_s, class: 'form-control col-sm-4'
  %p.help-block Separate with commas

= render 'project_type', f: f
= render 'build_setup', f: f
= render 'tracker_setup', f: f

= f.hidden_field :id
%hr
  .row
    .col-sm-offset-2.col-sm-1
      = submit_tag @project.new_record? ? 'Create' : 'Update', class: 'btn btn-primary'
    .pull-right
      - if !@project.new_record?
        = link_to 'Remove Project', project_path(@project), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

.row
  %p.text-muted.text-center Server time is #{Time.now}

app/views/projects/_project_type.html.haml
%hr
%fieldset#project_type_section
  %h3 Project Type
  .form-group
    = f.label :type, 'Provider', class: 'col-sm-2 control-label'
    .col-sm-3
      = f.select :type, project_types, {}, class: 'form-control'
  - ProjectsHelper::PROJECT_TYPE_NAMES.each do |project_type|
    - enabled = f.object.type == project_type.name
    .provider-specific{ class: "#{'hide' unless enabled} #{project_type}" }
      .col-md-2
      .col-md-10.build_setup_instructions= preserve(build_setup_instructions_for(project_type).html_safe)

app/views/projects/_tracker_setup.html.haml
%hr
%fieldset#tracker_setup
  %h3 Tracker Setup
  .form-group
    = f.label :tracker_project_id, 'Tracker project id', class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :tracker_project_id, class: 'form-control'
    %p.help-block
      %span#project_tracker_project_id_status
        %span.label.label-success.success.hide &#10004;
        %span.label.label-danger.failure.hide &#10008;
  .form-group
    = f.label :tracker_auth_token, 'Tracker auth token', class: 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :tracker_auth_token, class: 'form-control'
    %p.help-block
      %span#project_tracker_auth_token_status
        %span.label.label-success.success.hide &#10004;
        %span.label.label-danger.failure.hide &#10008;
  .form-group
    = f.label :tracker_online, 'Tracker status', class: 'col-sm-2 control-label'
    = f.hidden_field :tracker_online
    .col-sm-2#tracker_status
      %p.help-block
        %span.label.label-success.success.hide OK
        %span.label.label-info.pending.hide &nbsp;
        %span.label.label-default.unconfigured.hide Unconfigured
        %span.label.label-danger.failure.hide

app/views/projects/edit.html.erb
<%= link_to '&larr; Back to Projects'.html_safe, projects_path %>

<h1>Edit Project</h1>

<%= error_messages_for :project %>

<%= form_for(@project, :as => :project, :url => project_path, :html => {:method => :put}) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

<div style="margin-left: 30px;">
  <%= link_to 'Remove Project -', project_path(@project), data: { confirm: 'Are you sure?' }, method: :delete, class: "button" %>
</div>

app/views/projects/edit.html.haml
- content_for :head do
  = javascript_include_tag 'project'

= link_to '&larr; Back to Projects'.html_safe, edit_configuration_path
%h1 Edit Project
%hr
= error_messages_for @project
= form_for(@project, as: :project, url: project_path(@project), html: { class: 'form-horizontal' }) do |f|
  = render 'form', f: f

app/views/projects/index.html.erb
<h1>Projects</h1>

<%= link_to 'Add Project +', new_project_path, :class => "button add_button" %>

<table class="projects">
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Project Type</th>
    <th>Enabled?</th>
    <th>Aggregate</th>
    <th>Tags</th>
    <th>Webhook URL</th>
    <th>Actions</th>
    <th>Remove</th>
  </tr>

  <% for project in @projects %>
    <tr id="project-<%= project.id %>" class="<%= cycle("odd", "even") %>">
      <td><%= h project.code %></td>
      <td><%= h project.name %></td>
      <td>
        <%= content_tag 'span', project.class.name.titleize, :title=>"#{project.feed_url}#{project.has_auth? ? ' (under auth)' : ''}" %>
        <%= image_tag("icons/lock.png", :style => "position:relative; top: 3px;") if project.has_auth? %>
      </td>
      <td style="text-align: center;">
        <% if project.enabled? %>
          &#10003;
        <% else -%>
          <span style="color: #AA1224;">&#10005;</span>
        <% end -%>
      </td>
      <td style="text-align: center;"><%= project.aggregate_project.present? ? project.aggregate_project.name : "" %></td>
      <td class="tag_list"><%= project.tag_list %></td>
      <td><%= project_status_url(project) %></td>
      <td>
        <%= link_to 'Edit', edit_project_path(project), :class => "button" %>
      </td>
      <td>
        <%= link_to 'Delete', project_path(project), :method => :delete, :class =>"button" %>
      </td>
    </tr>
  <% end %>
</table>

<h1>Aggregate Projects</h1>

<%= link_to 'Add Aggregate Project +', new_aggregate_project_path, :class => "button add_button" %>

<table class="projects">
  <tr>
    <th>Name</th>
    <th>Enabled?</th>
    <th>Tags</th>
    <th>Actions</th>
    <th>Remove</th>
  </tr>

  <% reset_cycle -%>
  <% for aggregate_project in @aggregate_projects %>
    <tr id="aggregate-project-<%= aggregate_project.id %>" class="<%= cycle("odd", "even") %>">
      <td><%= h aggregate_project.name %></td>
      <td style="text-align: center;">
        <% if aggregate_project.enabled? %>
          &#10003;
        <% else -%>
          <span style="color: #AA1224;">&#10005;</span>
        <% end -%>
      </td>
      <td class="tag_list"><%= aggregate_project.tag_list %></td>
      <td>
        <%= link_to 'Edit', edit_aggregate_project_path(aggregate_project), :class => "button" %>
      </td>
      <td>
        <%= link_to 'Delete', aggregate_project_path(aggregate_project), :method => :delete, :class =>"button" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/projects/index.html.haml
%h1 Projects
= link_to 'Add Project +', new_project_path, :class => "button add_button"
%table.projects
  %tr
    %th Code
    %th Name
    %th Project Type
    %th Enabled?
    %th Aggregate
    %th Tags
    %th Webhook URL
    %th Actions
    %th Remove
  - for project in @projects
    %tr{:class => cycle("odd", "even"), :id => "project-#{project.id}"}
      %td= h project.code
      %td= h project.name
      %td
        = content_tag 'span', project.class.name.titleize, :title=>"#{project.feed_url}#{project.has_auth? ? ' (under auth)' : ''}"
        = image_tag("icons/lock.png", :style => "position:relative; top: 3px;") if project.has_auth?
      %td{:style => "text-align: center;"}
        - if project.enabled?
          ✓
        - else
          %span{:style => "color: #AA1224;"} ✕
      %td{:style => "text-align: center;"}= project.aggregate_project.present? ? project.aggregate_project.name : ""
      %td.tag_list= project.tag_list
      %td= project_status_url(project)
      %td
        = link_to 'Edit', edit_project_path(project), :class => "button"
      %td
        = link_to 'Delete', project_path(project), :method => :delete, :class =>"button"
%h1 Aggregate Projects
= link_to 'Add Aggregate Project +', new_aggregate_project_path, :class => "button add_button"
%table.projects
  %tr
    %th Name
    %th Enabled?
    %th Tags
    %th Actions
    %th Remove
  - reset_cycle
  - for aggregate_project in @aggregate_projects
    %tr{:class => cycle("odd", "even"), :id => "aggregate-project-#{aggregate_project.id}"}
      %td= h aggregate_project.name
      %td{:style => "text-align: center;"}
        - if aggregate_project.enabled?
          ✓
        - else
          %span{:style => "color: #AA1224;"} ✕
      %td.tag_list= aggregate_project.tag_list
      %td
        = link_to 'Edit', edit_aggregate_project_path(aggregate_project), :class => "button"
      %td
        = link_to 'Delete', aggregate_project_path(aggregate_project), :method => :delete, :class =>"button"

app/views/projects/new.html.erb
<%= link_to '&larr; Back to Projects'.html_safe, projects_path %>

<h1>Add Project</h1>

<%= error_messages_for :project %>

<%= form_for(@project, :as => :project, :url => projects_path) do |f| %>
  <%= render 'form', :f => f %>
<% end %>

app/views/projects/new.html.haml
- content_for :head do
  = javascript_include_tag 'project'

= link_to '&larr; Back to Projects'.html_safe, edit_configuration_path
%h1 Add Project
%hr
= error_messages_for @project
= form_for(@project, as: :project, url: projects_path, html: { class: 'form-horizontal' }) do |f|
  = render 'form', f: f