config/routes.rb
ProjectMonitor::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", sessions: "sessions" }
  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  get 'builds' => "home#builds", format: :rss
  get 'version' => 'versions#show'
  get 'github_status' => 'home#github_status', format: :json
  get 'heroku_status' => 'home#heroku_status', format: :json
  get 'rubygems_status' => 'home#rubygems_status', format: :json

  post 'projects/validate_tracker_project'
  patch 'projects/validate_build_info'

  resource :configuration, only: [:show, :create, :edit], controller: "configuration"
  resources :users, only: [:new, :create]
  resources :projects do
    resources :payload_log_entries, only: :index
    resource :status, only: :create, controller: "status"
    member do
      get :status
    end
  end
  resources :aggregate_projects do
    member do
      get :status
    end
    resources :projects, only: [:index]
  end

  authenticate :user do
    get "/jobs" => DelayedJobWeb, anchor: false
  end

  get 'styleguide' => 'home#styleguide'
  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Monitor</title>
    <%= stylesheet_link_tag "application" %>
    <%= yield :head %>
  </head>
  <body>

    <div id="header">
      <%= link_to(image_tag('pivotallabs-logo.png', :class => 'company_logo'), '/') %>
      <%= link_to(image_tag('ci-logo.png'), '/') %>
      <div id="top_right">
        <% if current_user.present? %>
          Hello, <%= current_user.login %>
          <%= link_to "(log out)", logout_path, :class=>'smaller_text' %>
          <br />
          <%= link_to "Projects", projects_path %>
          |
          <% if AuthConfig.password? %>
            <%= link_to "Add User", new_user_path %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="page <%= params[:controller] %> <%= params[:action] %>">
      <% if flash[:error] %>
        <div id="flash_error">
          <%= flash[:error] %>
        </div>
      <% end %>

      <% if flash[:notice] %>
        <div id="flash_notice">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Project Monitor
    = stylesheet_link_tag 'manage'
    = javascript_include_tag 'application'
    = javascript_include_tag 'bootstrap'
    = csrf_meta_tag
    = yield :head
  %body
    %nav.navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          .navbar-brand
            = link_to edit_configuration_path do
              = image_tag 'logo.png'
              = image_tag 'powered_by.png'

        .collapse.navbar-collapse
          - if current_user.present?
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a.dropdown-toggle{ data: { toggle: 'dropdown' }, href: '#' }
                  Hello, #{current_user.login}
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'Projects', edit_configuration_path
                  - if ConfigHelper.get(:password_auth_enabled)
                    %li
                      = link_to 'Add User', new_user_path
                  %li.divider
                  %li
                    = link_to 'Log Out', destroy_user_session_path, method: :delete
    .container
      %div{class: "page #{params[:controller]} #{params[:action]}"}
        - if flash[:error]
          .alert.alert-danger
            = flash[:error]
        - if flash[:notice]
          .alert.alert-success
            = flash[:notice]
        = yield

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Monitor</title>
    <%= stylesheet_link_tag "dashboard" %>
    <script type="text/javascript" src="http://fast.fonts.com/jsapi/14aea2b8-37b7-4a31-afb9-e44414bef419.js"></script>
  </head>
  <body class="dashboard tiles_<%= @tiles.size %>" data-tiles-count="<%= @tiles.size %>">
    <%= yield %>

    <div id="footer">
      <div class="left">
        Layout:
        <%= link_to "15", root_path(tiles_count: 15), class: "projects_path" %>
          |
        <%= link_to "24", root_path(tiles_count: 24), class: "projects_path" %>
          |
        <%= link_to "48", root_path(tiles_count: 48), class: "projects_path" %>
          |
        <%= link_to "63", root_path(tiles_count: 63), class: "projects_path" %>
          |
        <%= link_to "locations", root_path(view: "locations"), class: "projects_path" %>
      </div>

      <div class="right">
        <% if current_user %>
          <%= link_to "log out", logout_path, class: "projects_path" %>
          |
        <% end %>
        <div id='indicator'>
          <%= image_tag "indicator.gif", :title => "indicator", :alt => "indicator" %>
        </div>
        <%= link_to "manage projects", projects_path, class: "projects_path" %>
      </div>
    </div>

    <%= javascript_include_tag "dashboard" %>
  </body>
</html>

app/views/layouts/dashboard.html.haml
!!!
%html
  %head
    %title Project Monitor
    = stylesheet_link_tag "dashboard"
    = javascript_include_tag "application"
    = javascript_include_tag "dashboard"
    %script{:src => "http://fast.fonts.com/jsapi/14aea2b8-37b7-4a31-afb9-e44414bef419.js", :type => "text/javascript"}
  %body{:class => "dashboard tiles_#{@tiles_count}", "data-tiles-count" => @tiles_count}
    = yield
    #footer
      .left
      .right
        - if current_user
          = link_to "log out", destroy_user_session_path, class: "projects_path", method: :delete
          |
        #indicator
          = image_tag "indicator.gif", :title => "indicator", :alt => "indicator"
        = link_to "manage projects", edit_configuration_path, class: "projects_path"

app/views/layouts/default.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"/>
    <title><%= title %></title>
</head>

<%= yield %>

</html>

app/views/layouts/home.html.haml
!!!
%html
  %head
    %title Project Monitor
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    %script{src: '//fast.fonts.com/jsapi/14aea2b8-37b7-4a31-afb9-e44414bef419.js', type: 'text/javascript'}
  %body{class: "dashboard tiles_#{@tiles_count}", 'data-tiles-count' => @tiles_count}
    = yield
    #footer
      .left
      .right
        - if current_user
          = link_to 'log out', destroy_user_session_path, class: 'projects_path', method: :delete
          |
        - if params[:limit] != 'all'
          = link_to 'show all projects', root_path(limit: :all), class: 'projects_path'
          |
        = link_to 'manage projects', edit_configuration_path, class: 'projects_path'
      .clearfix